# Generated by Django 2.0 on 2017-12-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('number_pages', models.IntegerField()),
                ('type_book', models.CharField(max_length=250)),
            ],
        ),
    ]
